name: build with nix

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest']
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31.2.0
    - uses: cachix/cachix-action@v16
      with:
        name: tket
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        installCommand: "nix profile install --accept-flake-config nixpkgs#cachix"
    - name: Build pytket-cutensornet
      run: nix build --accept-flake-config
  test:
    needs: build
    runs-on: cuda
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31.2.0
    - uses: cachix/cachix-action@v16
      with:
        name: tket
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        installCommand: "nix profile install --accept-flake-config nixpkgs#cachix"
    - name: Test pytket-cutensornet
      # impure is necessary due to nixgl usage (system-dependent cuda)
      run: nix run .#tests --impure --accept-flake-config
    - name: Test example notebooks
      # impure is necessary due to nixgl usage (system-dependent cuda)
      run: nix run .#example-tests --impure --accept-flake-config
