name: Lint python projects

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'wheel/**'
      - 'runci/**'

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Update pip
      run: pip install --upgrade pip
    - name: Install black and pylint
      run: pip install black pylint
    - name: Check files are formatted with black
      run: |
        black --check .
    - name: Run pylint
      run: |
        pylint --recursive=y pytket/extensions/cutensornet/
